cc_library(
    name = "newton_method",
    hdrs = [
        "newton_method.h",
        "newton_method_linear_search.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//core/BaseMath:function",
        "//core/ConvexOptimization/StepSearch:armijo",
    ],
)
