cc_library(
    name = "phr_augmented_lagrangian_method",
    hdrs = ["phr_augmented_lagrangian_method.h"],
    visibility = ["//visibility:public"],
    deps = ["//core/ConvexOptimization/QuasiNetwonMethod:quasi_newton_method"],
)
