cc_test(
    name = "barrier_method_test",
    srcs = ["barrier_method_test.cpp"],
    deps = [
        "//core/ConvexOptimization/Constrained_Optimization/BarrierMethod:barrier_method",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
