cc_test(
    name = "phr_augmented_lagrangian_method_test",
    srcs = ["phr_augmented_lagrangian_method_test.cpp"],
    deps = [
        "//core/ConvexOptimization/Constrained_Optimization/PRHAgumentedLagrangianMethod:phr_augmented_lagrangian_method",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
