cc_test(
    name = "bfgs_test",
    srcs = ["bfgs_test.cpp"],
    deps = [
        "//core/ConvexOptimization/QuasiNetwonMethod:quasi_newton_method",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
