cc_test(
    name = "penalty_method_test",
    srcs = ["penalty_method_test.cpp"],
    deps = [
        "//core/ConvexOptimization/Constrained_Optimization/PenaltyMethod:penalty_method",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
