cc_test(
    name = "function_test",
    srcs = ["function_test.cpp"],
    copts = ["-std=c++17"],
    deps = ["@gtest//:gtest",
    "@gtest//:gtest_main",
     "//core/BaseMath:function",
     "//core/BaseMath:container",
    ]
)