cc_library(
    name = "steepest_gradient_descent",
    hdrs = ["steepest_gradient_descent.h"],
    srcs = ["steepest_gradient_descent.cpp"],
    copts = ["-std=c++17","-Wall", "-Werror", "-Wextra"],
    deps = ["//core/BaseMath:function",
            "@com_github_google_glog//:glog"],
    visibility = ["//visibility:public"],
)