cc_library(
    name = "armijo",
    srcs = [],
    hdrs = ["armijo_condition.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/BaseMath:function",
        "//core/ConvexOptimization/utils",
        "//logging:log",
    ],
)
