cc_library(
    name = "armijo",
    srcs = [],
    hdrs = ["armijo_condition.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/BaseMath:function",
        "//core/ConvexOptimization/utils",
        "//logging:log",
    ],
)

cc_library(
    name = "wolfe",
    srcs = [],
    hdrs = ["wolfe_condition.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/BaseMath:function",
        "//core/ConvexOptimization/utils",
        "//logging:log",
    ],
)

cc_library(
    name = "lewis_overton_condition",
    srcs = [],
    hdrs = ["lewis_overton_condition.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/BaseMath:function",
        "//core/ConvexOptimization/utils",
        "//logging:log",
    ],
)
