cc_test(
    name = "armijo_test",
    srcs = [
        "armijo_test.cpp",
    ],
    copts = ["-std=c++17"],
    deps = [
        "//core/ConvexOptimization/StepSearch:armijo",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
