cc_library(
    name = "quasi_newton_method",
    hdrs = [
        "bfgs.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//core/BaseMath:function",
        "//core/ConvexOptimization/StepSearch:armijo",
    ],
)
