cc_test(
    name = "utils_test",
    srcs = [
        "utils_test.cpp",
    ],
    copts = ["-std=c++17"],
    deps = [
        "//core/ConvexOptimization/utils",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
