cc_test(
    name = "newton_method_test",
    srcs = ["newton_method_test.cpp"],
    deps = [
        "//core/ConvexOptimization/NewtonMethod:newton_method",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "newton_method_linear_search_test",
    srcs = ["newton_method_linear_search_test.cpp"],
    deps = [
        "//core/ConvexOptimization/NewtonMethod:newton_method",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
